version: "3.8"

services:
  api:
    image: easydictionary:latest
    container_name: easydictionary-api
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend-net
    depends_on:
      - postgres
    environment:
      - DB_HOST=${SERVER_CONFIG_DB_HOST}
      - DB_PORT=${SERVER_CONFIG_DB_PORT}
      - DB_USER=${SERVER_CONFIG_DB_USER}
      - DB_PASSWORD=${SERVER_CONFIG_DB_PASSWORD}
      - DB_NAME=${SERVER_CONFIG_DB_NAME}
      - SERVER_CONFIG_TIMEOUT=${SERVER_CONFIG_TIMEOUT}
      - SERVER_CONFIG_PORT=${SERVER_CONFIG_PORT}
      - SERVER_CONFIG_ADDRESS=${SERVER_CONFIG_ADDRESS}
      - SERVER_CONFIG_JWT_SECRET=${SERVER_CONFIG_JWT_SECRET}
      - SERVER_CONFIG_JWT_EXP_TIME_MINUTES=${SERVER_CONFIG_JWT_EXP_TIME_MINUTES}
      - APP_ENV=${APP_ENV}

  postgres:
    image: postgres:16-alpine
    container_name: easydictionary-postgres
    restart: always
    environment:
      POSTGRES_USER: ${SERVER_CONFIG_DB_USER}
      POSTGRES_PASSWORD: ${SERVER_CONFIG_DB_PASSWORD}
      POSTGRES_DB: ${SERVER_CONFIG_DB_NAME}
    networks:
      - backend-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  swagger:
    image: swaggerapi/swagger-ui
    container_name: easydictionary-swagger
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/usr/share/nginx/html/swagger/swagger.json
    volumes:
      - /home/deployuser/deploy/swagger:/usr/share/nginx/html/swagger:ro

volumes:
  postgres_data:
  
networks:
  backend-net:
