name: Deploy DEV to VPS

on:
  workflow_dispatch:
  push:
    branches:
      - main #change to dev after production release

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0' #similar with local build

      - name: Build Go Binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o easydictionary ./cmd
      
      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger Docs
        run: swag init --generalInfo ./cmd/main.go --dir ./api/controller --output ./docs --parseDependency

      - name: Copy swagger.json to swagger folder
        run: |
          mkdir -p swagger
          cp ./docs/swagger.json ./swagger/swagger.json

      - name: Copy files to server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_IP }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          source: "easydictionary,docker-compose.yml,dockerfile,swagger"
          target: "~/deploy"

      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_IP }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            cd ~/deploy
            docker build -t easydictionary:latest .

            docker-compose down
            docker-compose up -d --build
