name: Deploy DEV to VPS

on:
  workflow_dispatch:
  push:
    branches:
      - main #change to dev after production release

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.0" #similar with local build

      - name: Build Go Binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o easydictionary ./cmd

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger Docs
        run: swag init --generalInfo cmd/main.go --output ./docs --parseDependency --parseInternal

      - name: Copy swagger.json to swagger folder
        run: |
          mkdir -p swagger
          cp ./docs/swagger.json ./swagger/swagger.json

      - name: Upload files via SCP (with alternative action)
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_IP }}
          user: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          pass: ""
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          connect_timeout: 30s
          local: |
            easydictionary
            docker-compose.yml
            dockerfile
            swagger-nginx.conf
          remote: ~/deploy/
          port: 22

      - name: Rsync swagger to server
        run: |
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key" ./swagger/ deployuser@${{ secrets.DEPLOY_SERVER_IP }}:/home/deployuser/deploy/swagger/
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key" ./swagger-nginx.conf deployuser@${{ secrets.DEPLOY_SERVER_IP }}:/home/deployuser/deploy/swagger/

      - name: Execute remote commands (build docker containers)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_IP }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            cd ~/deploy
            ls -la
            docker build -t easydictionary:latest .

            docker-compose down
            docker-compose up -d --build
